# Generated by Django 3.2.7 on 2021-11-27 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime', models.CharField(blank=True, max_length=25, null=True)),
                ('memory_usage', models.CharField(blank=True, choices=[('n', '  '), ('4GB', '4GB'), ('16GB', '16GB')], max_length=25, null=True)),
                ('cpu_usage', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diskpartitioninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, max_length=25, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device')),
            ],
        ),
    ]
